### ISSUE TITLE
Signing File gives error

### ISSUE THREAD

**Issue by Steinliiippp** [mareklinka/SafeNetTokenSigner#1]
If i try to sign a file i get this error:
Signing of the package failed in SignAppxPackage, error 0

I can open the token and find the certificate but what is error 0?

I use the pe mode ot sign a exe file

**Comment by mareklinka** [comment]
The error codes will most likely not be too helpful. One situation where signing a PE executable works and an AppX package fails is when the AppX's manifest differs from the certificate you are trying to use.

In the `Package.appxmanifest`, there is information about the package's publisher:

![image](https://user-images.githubusercontent.com/7479226/55898367-b7fb6600-5bc2-11e9-8daa-9bbe80d83301.png)

The `Publisher` field here must match the `Subject` of your code signing certificate **exactly**, otherwise the signing process will fail.

You can find more details in this documentation: [Sign an app package using SignTool - Common errors and troubleshooting](https://docs.microsoft.com/en-us/windows/uwp/packaging/sign-app-package-using-signtool#common-errors-and-troubleshooting)

The article describes SignTool.exe but under the hood that still uses the same APIs as this code so the errors should be pretty much the same.

**Comment by Steinliiippp** [comment]
But im trying to sign a PE executable (standard exe file). The same code works on my computer but fails on the server im trying to run the program. Here is some output from the code:

Certificate thumbprint: a764d30fbe1909e721*************
Timestamp URL: http://timestamp.digicert.com
File to sign: C:\Users\Administrator\Desktop\test.exe

Logging into the usb-token... 
Logging into usb-token le-94e7eb71-****************da5b0 / eToken Base Cryptographic Provider with PASSWORD
Unlocked usb-token
Successfully set CryptSetProvParamSuccess
Certificate store (on Computer) opened successfully
Certificate in digital computer store found
Signing file C:\Users\Administrator\Desktop\test.exe... MSSign32.dll was loaded 
SignerSignEx2 was loaded 
End of SignerSignEx2: 0
Signing of the package failed in SignAppxPackage, error 0

**Comment by mareklinka** [comment]
That is strange. Can you provide the exact command line you are using to sign your file? With the sensitive information edited out, of course. Also, what kind of file is the test.exe? Is it a .NET app? Native (C++)? Something else?

**Comment by Steinliiippp** [comment]
The command line is this:
C:\Users\Administrator\Desktop\SafeNetTokenSigner.exe "a764d3******************f83df87" "le-94e******************da5b0" "PASSWORD" "http://timestamp.digicert.com" "pe" "C:\Users\Administrator\Desktop\test.exe"

As far as i know it should be a native c++ executable but i could try it with something other too?

I have used the same commandline localy (with an other token) and it worked. I tried differen versions of SafeNet Driver and tried different versions of MSSign32.dll but nothing helps ....

Thanks for your help!

**Comment by Steinliiippp** [comment]
I tried it with the produced SafeNetTokenSigner.exe but i get the same error ....

**Comment by mareklinka** [comment]
When you tried with a different token, did it work with the same exe file? I'm not sure this will work for native executables (I haven't tried). It should work for .NET assemblies - C# console apps, for example.

**Comment by Steinliiippp** [comment]
Yes i used the same programm (exe file) on the server and locally. The only difference between local and server is, that the server has a other token plugged in. But i tested the token on my local system before i send it to the server and it worked ...

**Comment by Steinliiippp** [comment]
Is there any possibility to get a more informativ error message?

**Comment by Steinliiippp** [comment]
I also got the error code 0x80070002 ... but 99% of all tries is 0

**Comment by mareklinka** [comment]
The thing with the error codes is that there is very little documentation on this. What might be helpful is printing the actual HRESULT that comes out of the SignFile function.

You could try adding
`std::wcerr << L"HRESULT " << std::hex << res << L"\n";`
after 
`HRESULT res = SignFile(pDesiredCert, fileToSign.c_str(), timestampUrl.c_str(), mode == L"appx");`

You could even omit the `std::hex`. That should give you the exact return code of the SignerSignEx2 function.

I'm not really a C++ developer  - I hope we can figure it out.

**Comment by Steinliiippp** [comment]
Here is the output without std::hex -2146885626 and this is with std:hex 80092006

Im really thankfull, that you try to help me!! Im also not really a c++ developer ... so ....

**Comment by mareklinka** [comment]
Alright, that seems more like it. 0x80092006 = CRYPT_E_NO_PROVIDER which would indicate that there is something wring with the provider opening. One thing that comes to mind - when you try this on the server, are you logged into the server via Remote Desktop? The SafeNet tokens have some countermeasures in place - basically, remote desktop will disable the token, more or less.

**Comment by Steinliiippp** [comment]
I am logged in with RDP but i let the programm execute as System user. If i try it directly with RDP i get errors on opening the token. So i tought that is would work with the System-Thread ... maybe it does not ... how do you start it on the server?

**Comment by Steinliiippp** [comment]
I think i will try it with KCM (Remote Console) where you can see the boot messages and so on. For Windows it must look like a local user ... if it works i know the problem. If not i must be something different.

**Comment by Steinliiippp** [comment]
Ok im working with the KVM Console. If i use the program it fails with the same error. But i can use signtool as i would on a normal computer and it works ... WHAT? I dont understand this ...

**Comment by mareklinka** [comment]
That is weird, really. At any rate, I'm currently doing some work on this. The changes will be:
1. Port the code to C# and make it a dotnet global tool (for people who want to use it for .NET solutions) and push it to nuget
2. Improve the error handling of the original C++ code so that it's easier to debug these situations

It might take a few days before these are ready, however.

**Comment by Steinliiippp** [comment]
Wow that is great! Thank you very very mutch!!

During my research i found this registry entry where you can find all installed smart cards.
I can find my SafeNet eToken.

Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Cryptography\Defaults\Provider\

Maybe it helps during development?

**Comment by mareklinka** [comment]
Alright, so the initial version of the .NET port is live: https://github.com/mareklinka/SafeNetTokenSigner/releases/latest

It should have much better error messages so it should be easier to debug your problem. It's a pre-release version but you might want to give it a try to see if it helps. You may also want to build it yourself if you feel like it but I provided pre-built binaries.

To run it, you will need the [.NET Core 2.2 runtime](https://dotnet.microsoft.com/download) installed on the machine and run on x64 Windows 8+ (or Server 2012+).

Let me know if you decide to try this out and if it helps at all.

**Comment by Steinliiippp** [comment]
I tried it and get this error: Keyset does not exist (Exception from HRESULT: 0x80090016)

**Comment by Steinliiippp** [comment]
Ahh i did not look into your code ... maybe its the problem that he does not find the public key. In the c++ programm i replaced CERT_SYSTEM_STORE_CURRENT_USER with CERT_SYSTEM_STORE_LOCAL_MACHINE because i must invoke the program as system user but can only install the certificate over rdp as admin user? Could you search on both places?

**Comment by mareklinka** [comment]
The current user store is hardcoded because the SafeNet app has a setting to "Export the public key into the current user's store" so whichever user is logged in, they should see the cert in their store. I could add a setting to choose which store to use, if you think it will help. But maybe check if this setting is enabled on the token - it might be easier to do that way.

When testing, I managed to trigger the `Keyset does not exist` error when I specified an invalid container name (the second parameter) so that's also worth checking out.

I will look into the option for specifying machine store tomorrow.

**Comment by mareklinka** [comment]
It's also important that the code only works for the certificate under `Personal` certificates:

![image](https://user-images.githubusercontent.com/7479226/55984586-18aba100-5c9e-11e9-82f4-44b9aa348fb2.png)

Since I get the feeling you are installing the certificate manually, this might also be a problem - if you install it under some other folder, the current code base won't find it.

**Comment by Steinliiippp** [comment]
Ok ... i have to say sry ... i forgett to unpluck my local token which is parsed over remote desktop ... so now i can unlock the token on the server and get this error:

The specified module could not be found. (Exception from HRESULT: 0x8007007E)

**Comment by mareklinka** [comment]
Ah, progress! 😄 What version of Windows is the server running?

**Comment by Steinliiippp** [comment]
It runs Windows Server 2019 Standard ... yeah progress ... thanks for your patience 😄

**Comment by Steinliiippp** [comment]
The problem must be in the `private static void SignFile(IntPtr certificate, string path, string timestampUrl, SignMode type)` method.

**Comment by mareklinka** [comment]
That is strange. That particular error looks like the system cannot find a module. The only module I load dynamically is `MSSign32.dll`. Can you provide the entire program output? Does it say something like `Win32 error in LoadLibraryEx: The specified module could not be found.`?

**Comment by Steinliiippp** [comment]
I found the error just right now ... i dont know why he cannot find the dll but i could set a fixed path and now it goes on ... but still failing ... 

No provider was specified for the store or object. (Exception from HRESULT: 0x80092006)

**Comment by Steinliiippp** [comment]
I found this on https://stackoverflow.com/questions/14237289/signersign-error-no-provider-was-specified-for-the-store-or-object

`ICspAsymmetricAlgorithm key = (ICspAsymmetricAlgorithm)certificate.PrivateKey;
const int PVK_TYPE_KEYCONTAINER = 2;

var providerInfo = new SignerProviderInfo
{
   cbSize = (uint)Marshal.SizeOf(typeof(SignerProviderInfo)),
   pwszProviderName = key.CspKeyContainerInfo.ProviderName,
   dwProviderType = (uint)key.CspKeyContainerInfo.ProviderType,
   dwPvkChoice = PVK_TYPE_KEYCONTAINER,
   providerUnion = new SignerProviderInfo.ProviderInfoUnion
   {
       pwszKeyContainer = key.CspKeyContainerInfo.KeyContainerName
   },
};`

**Comment by mareklinka** [comment]
That parameter should not be required in this particular setup, according to the docs. I added pushed version 0.1.2 with progress logging. When you can, please try it and post the full output (a screenshot should be fine). Only then I can try and figure out where exactly the code fails.

Thanks a lot for the effort!

EDIT

Oh, and the new code requires a new parameter: `<exe> <certificate thumbprint> <private key container name> **<target store>** <token PIN> <timestamp URL> <path to file to sign>`

Target store can be either `user` or `machine`.

**Comment by Steinliiippp** [comment]
![image](https://user-images.githubusercontent.com/3447780/55990353-c8d1d780-5ca7-11e9-8ca8-89d465d02d34.png)

I used your code only with the modification of a direct path to the MSSign32.dll

**Comment by mareklinka** [comment]
Ok. That tells me that basically everything works. You can open the store, find the certificate, load MSSign32, load the signing function... EXCEPT the actual signing operation.

The fact that you tried this on your local machine and it worked (but fails on the server) tells me there is something weird going on either with Server 2019 (don't have that accessible to try) or with how the certificate is set up on the server.

People usually hit this error "No provider was specified" when the private key cannot be accessed. Since I don't know how exactly you import the certificate into the store, I can only speculate. One possibility would be that the system user (the one under which you run the tool) does not have rights to access the private key?

**Comment by Steinliiippp** [comment]
I found something interessting:

1. I connected wit RDP and use my local smart card. I can see the smart card in SafeNet Client. If i use your program i get a popup from Windows on "Invoking SignerSignEx2" to choose a smart card. No matter what i choose i get an error in the popup. When i press cancel the same error message appears (picture).

2. When i use RDP with my local smart card an invoke signtool.exe i get the same question from windows. No matter what i choose i get an error in the dialog. When i press cancel a popup from SafeNet comes up and if i enter the password the file gets signed.

So maybe the program does not know which smart card to use? There are other Windows Smart-Cards in the registry (i think virtual ones).

PS: I changed the container id to the local one before testing 😄

**Comment by mareklinka** [comment]
That is an interesting piece of information. I only have one token so this did not come up. I think the best course of action would be to figure out the signtool command that works and then trying to replicate it.

There should be a combination of the /csp, /kc, /s, and /sm parameters that should work. The trick will be figuring out which one it is.
________________________________

**Comment by mareklinka** [comment]
Reading up on CSPs a little more, it seems in your case we will really need to populate the optional `pProviderInfo ` parameter, similar as in the StackOverflow question you linked. The application should have all the data for it so it should be relatively simple. Just need to create the proper struct and feed it into the `SignerSignEx2` call.

I *think* your attempt in 1. fails because the tool acquires the cryptographic context in silent mode, so no UI can be displayed. That might be why SignTool behaves a little differently (showing the PIN prompt).

**Comment by mareklinka** [comment]
So I added the code that fills in the provider info. Not sure if it will help but no harm in trying. It's currently in branch `feature/ProviderInfo`. Try giving it a spin to see if it helps.

**Comment by Steinliiippp** [comment]
I will try it when i am at home! I can not tell you how thankful I am! No matter if it works or not ... you are just great! Thanks!

**Comment by Steinliiippp** [comment]
OMG! It is working! You are just great! Thank you very very ... very .... much!!!!!!

Should you ever have any Java programming related problem, I'm would be really happy to help!

**Comment by mareklinka** [comment]
Awesome! 💯 

Glad I could make it work for you. I'll be doing some additional work on the code over the weekend, reworking the way command line arguments are handled and some such. I'll also add some options to specify where to load the `MSSign32.dll` from just in case the default search won't work. Version 0.2 should be available next week, if everything goes right.

But for now, thanks for sticking with me through this, I'd never be able to debug this situation without your help. Closing the issue, if you need anything else, reopen or create another one.

Cheers 😄
